### ISSUE TITLE
Unable to print from client on same subnet

### ISSUE THREAD

**Issue by rahul-thakoor** [willswire/balenaPrint#1]
Unable to print from a shared printer on the network unless I also enable "Allow printing from the internet" in server settings: 
![image](https://user-images.githubusercontent.com/13220877/73645580-02d5f500-4691-11ea-82ac-814be7d3e1b4.png)

**Expected behavior:**
When sharing a printer, clients on the same network should be able to print to that printer. 

**Actual behavior**:
The client is able to discover printer but when trying to print, presented with _"You do not have permission to use this printer"_. Must enable Allow printing from the internet" in server settings for it to work.

**Comment by rahul-thakoor** [comment]
hey @willswire do you know how we can enable that automatically in the conf file or modify it so that it handles jobs on the same network?

have you experienced this issue?

**Comment by rahul-thakoor** [comment]
```diff
--- a/cups/cupsd.conf
+++ b/cups/cupsd.conf
@@ -3,10 +3,8 @@
 # Log warning activity
 LogLevel warn
 PageLogFormat
-
-# Listen on Port 80
-Listen 80
-Listen 631
+# Allow remote access
+Port 80
 Listen /run/cups/cups.sock

 # Modify ServerAlias
@@ -25,8 +23,9 @@ WebInterface Yes

 # Open access to the server
 <Location />
+  # Allow remote access...
   Order allow,deny
-  Allow from 52.4.252.97
+  Allow all
 </Location>

 # Open access to the admin pages
```

this seems to enable it. Any thoughts? Can we upstream this?

**Comment by willswire** [comment]
@rahul-thakoor these changes look good! can you submit a PR and we can get them upstreamed?

Sorry for the late response - I appreciate your contribution! 😁
