### ISSUE TITLE
need guide workflow for printer requires proprietary plugins

### ISSUE THREAD

**Issue by fansijou** [willswire/balenaPrint#15]
i'm using HP Color Laserjet Pro CP 1025, when running Balena-CUPS install printer driver, appeared this printer requires proprietary plugins. if do nothing about this plugin, after install Balena-CUPS pop-up printer driver for CP 1025, then print job can not finish normally, error happed say "filter failed".

so i guess i should follow the guide to install required plugins, but i can not find any guide to do so.

**Comment by joao-vasconcelos** [comment]
In Balena Dashboard, start a new Terminal session targeting the CUPS container.
Run `hp-setup -i` (-i stands for interactive)
Follow the steps, and be _very_ patient — it can take like 20 minutes for it to connect, find the driver, etc. It seems like it is stuck but is in fact working.
Good luck!

**Comment by willswire** [comment]
@fansijou, please reopen this issue if you have questions. Marking it closed
