### ISSUE TITLE
HPLIP should be installed along with CUPS

### ISSUE THREAD

**Issue by SonicMike** [willswire/balenaPrint#6]
Many HP printers require binary blobs to be installed for them to work.  HP provides them with an installer HPLIP - https://developers.hp.com/hp-linux-imaging-and-printing.  Could this be installed on your image?

**Comment by willswire** [comment]
@SonicMike thanks for opening this issue!

The hplip package is included in the Dockerfile. Does this package not include the required binary blobs you are mentioning?

**Comment by SonicMike** [comment]
> 
> 
> @SonicMike thanks for opening this issue!
> 
> The hplip package is included in the Dockerfile. Does this package not include the required binary blobs you are mentioning?

I saw that HPLIP was mentioned, after adding this issue, in the tutorial on the Balena blog.  Sorry for not checking the directions more closely. When I add my printer CUPS finds it and in the next step there's 7 identical drivers to choose from. They are titled "HP LaserJet 1020, hpcups 3.18.12, requires proprietary plugin (en)" so I assumed that the proprietary plugin was something that was missing.  My printer is very old so I'm not surprised that its difficult to get working. It did work with Ubuntu however.  Printing the test page fails when connected to my RPI. I'll try redoing the steps from the Blog to see if that helps.

**Comment by willswire** [comment]
@SonicMike any luck after running through the tutorial again?

**Comment by SonicMike** [comment]
After I did some research I found out that the cause of the problem was hpcups and that foo2zjs  would drive the printer without issue.  So that's what I ended up doing.  This printer is very old and quirky (it needs firmware sent to it to work).

**Comment by willswire** [comment]
Gotcha! Since you were able to resolve the issue, I am going to mark this topic as closed. Thanks!

**Comment by fansijou** [comment]
@SonicMike so what did you do exactly for this? i'm using HP Color Laserjet Pro CP 1025, here is same issue when use hplip, but foo2zjs driver is work for it. But i dont know how to include this foo2zjs driver into Balena-CUPS.
@willswire would you please also come out some guide about how to do include foo2zjs driver? checked steps on blog, see "this requires manually installing the drivers and plugins" for these printers equire proprietary plugins:
