### ISSUE TITLE
Readme missing Deploy with balena button

### ISSUE THREAD

**Issue by andrewnhem** [willswire/balenaPrint#9]
@willswire I was looking through some user analysis and your project drives a lot of installations using our Deploy with balena method. I realized that a lot of that traffic is from our blog post about your project. I noticed that your readme doesn't have the button.

I tried to send a PR with a prospective fix, but didn't have authorization to submit. If you're interested in doing this, I'm more than happy to add it. Or if you want the raw content to edit yourself, happy to submit that as well.

Just let me know. If not here, at andrewn@balena.io. Thanks for your hard work!

**Comment by willswire** [comment]
@andrewnhem thanks for the comment! Please feel free to make the PR and I'll merge it in.

**Comment by andrewnhem** [comment]
Thanks @willswire . Feedback is always welcome!

**Comment by willswire** [comment]
Ref #10
